spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./flashcards-db/db

logging:
  level:
    com.example.flashcards: DEBUG

security:
  jwt:
    secret: jwt.super.secret.key
    expiration-time-minutes: 10080